version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: stock-market-api-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: stockmarketapi
      TZ: Asia/Seoul
      MYSQL_DATABASE: stock
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64